name: linting
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Repo clone
      uses: actions/checkout@v4
    - name: install html hint
      run: npm install --save-dev htmlhint
    - name: install style lint
      run: npm install --save-dev stylelint
    - name: linting html
      run: npx htmlhint "**/*.html"
    - name: linting style
      run: npx stylelint "**/*.css"